[colors]
selection = { text = "#ffffff", background = "#686868" }

[colors.primary]
foreground = "#ffffff"
background = "#000000"
dim_foreground = "#ffffff"
bright_foreground = "#ffffff"

[colors.normal]
black = "#000000"
red = "#b21818"
green = "#18b218"
yellow = "#b26818"
blue = "#1818b2"
magenta = "#b218b2"
cyan = "#18b2b2"
white = "#b2b2b2"

[colors.bright]
black = "#646464"
red = "#ff5454"
green = "#54ff54"
yellow = "#ffff54"
blue = "#5454ff"
magenta = "#ff54ff"
cyan = "#54ffff"
white = "#ffffff"

[colors.dim]
black = "#181818"
red = "#650000"
green = "#006500"
yellow = "#654a00"
blue = "#000065"
magenta = "#5f055f"
cyan = "#18b2b2"
white = "#656565"
