# Prompt
add_newline = false
format = '$time $all$username$hostname $character'
right_format = '$sudo$cmd_duration'

[character]
success_symbol = '[λ](bold purple)'
error_symbol = '[λ](bold red)'

[cmd_duration]
min_time = 4000
format = ' [⏱ $duration]($style)'
style = 'bold green'

[directory]
truncation_length = 64
truncate_to_repo = false
style = 'bold cyan'
read_only = ' 󰌾'
repo_root_style = 'bold purple'

[git_branch]
symbol = ' '

[git_commit]
commit_hash_length = 8
tag_disabled = false
tag_symbol = '  '

[hostname]
ssh_only = false
format = '[@[$hostname]($style)\]](bold purple)'
style = 'bold green'

[sudo]
format = '[$symbol]($style)'
symbol = ' '
disabled = false

[time]
format = '[\[[$time]($style)\]](bold purple)'
style = 'bold green'
disabled = false

[username]
style_user = 'bold green'
format = '[\[[$user]($style)](bold purple)'
show_always = true

# Languages and technologies
[c]
symbol = ' '

[dart]
symbol = ' '

[docker_context]
symbol = ' '

[elixir]
symbol = ' '

[golang]
symbol = ' '

[gradle]
symbol = ' '

[haskell]
symbol = ' '

[helm]
detect_folders = ['helmfile.d']

[java]
symbol = ' '
style = 'bold red'

[kotlin]
symbol = ' '

[lua]
symbol = ' '

[package]
symbol = ' '

[python]
format = 'via [[${symbol}](blue)${pyenv_prefix}(${version} )(\\($virtualenv\\) )]($style)'
symbol = ' '
style = 'bold blue'

[rlang]
symbol = '󰟔 '

[ruby]
symbol = ' '

[rust]
format = 'via [[$symbol](red)($version )]($style)'
symbol = ' '

[scala]
symbol = ' '

[zig]
symbol = ' '
