#!/bin/bash
 
# Arbitrary but unique message tag
msgTag="dunst-brightness"

brightnessctl set "$@" > /dev/null
 
# Query brightnessctl for the current brightness
brightness="$(brightnessctl -m | cut -d , -f 4)"

# Show the brightness notification
dunstify -t 1600 -a "changeBrightness" -u low -h string:x-dunst-stack-tag:$msgTag -h int:value:"$brightness" "Brightness ${brightness}"
