#!/bin/bash

# Arbitrary but unique message tag
msgTag="dunst-low-battery"

# Query battery status and percentage
if [[ "$(acpi -b | awk '{print $3}' | tr -d ' ,')" == "Discharging" ]]; then
	charge="$(acpi -b | awk '{print $4}' | tr -d ' %,')"
	if [[ $charge -le 25 ]]; then
		# Show the low battery notification
		dunstify -t 0 -a "lowBattery" -u critical -h string:x-dunst-stack-tag:$msgTag "Low battery charge."$'\n'"Plug in your computer NOW."
	fi
fi
