#!/bin/bash

# Arbitrary but unique message tag
msgTag="dunst-low-battery"

function updateStatus() {
  status="$(acpi -b | awk '{print $3}' | tr -d ' ,')"
  return 0
}

# Query battery status and percentage
updateStatus
if [[ $status == "Discharging" ]]; then
  charge="$(acpi -b | awk '{print $4}' | tr -d ' %,')"
  if [[ $charge -le 25 ]]; then
    # Show the low battery notification
    dunstify -t 0 -a "lowBattery" -u critical -h string:x-dunst-stack-tag:$msgTag "Low battery charge"$'\n'"Computer is gonna sleep in 2 minutes" -i noicon
    sleep 2m
    updateStatus
    if [[ $status == "Discharging" ]]; then
      systemctl sleep
    fi
  fi
fi
