#!/bin/bash

set -euo pipefail

chordStart="super + o"

input=$(rg -C 1 "F(1|2)" $HOME/.dotfiles/sxhkdrc | sed 's/# //;;s/\t//')

declare -A dict

while IFS= read -r line; do
  if [[ $line == "--" || -z $line ]]; then
    continue
  fi
  read -r key
  read -r value
  dict["$key - $line"]=$value
done <<<"$input"

choice=$(printf '%s\n' "${!dict[@]}" | sort -g | dmenu -l 12 -mw 256) || exit 1

${dict["$choice"]}
