#!/bin/bash

set -euo pipefail

selected="$(ps -wu "$USER" -o pid,cmd --sort -%cpu,-%mem | sed -n '1!p' | dmenu | awk '{print $1" "$2}')"

if [[ -n $selected ]]; then
  answer="$(printf "No\nYes" | dmenu -p "Kill $selected?")"

  if [[ $answer == "Yes" ]]; then
    kill -9 "${selected%% *}"
    echo "Process $selected has been killed." && exit 0
  else
    echo "User choose not to kill a process." && exit 1
  fi
fi
