#!/bin/bash

set -euo pipefail

case "$(printf "Lock\nSleep\nPoweroff\nReboot\nLogout" | dmenu -l 5)" in
Lock) exec slock ;;
Sleep) exec systemctl suspend ;;
Poweroff) exec systemctl poweroff ;;
Reboot) exec systemctl reboot ;;
Logout) exec pkill dwm ;;
esac
