#!/bin/bash

sep="----------------------------------------------------------------"

next() {
  printf "\nPress any key to continue\n"
  read -n 1 -s -r
}

calling() {
  printf "\n%s\nCalling %s\n%s\n\n" $sep "$1" $sep
}

calling "topgrade"
topgrade
next

calling "yay -Sc"
yay -Sc
next

calling "docker system prune"
docker system prune
